### ISSUE TITLE
Locked up, reinstall doesn't help.

### ISSUE THREAD

**Issue by pyeager56** [bluecherrydvr/unity#54] opened 2023-01-26 23:18 UTC
I attempted to open the app to reproduce an issue.

All I got was a blank white window with the Bluecherry logo in the center.  Had to kill it with task manager.

Tried reinstalling.  No luck.  Uninstalled and reinstalled.  No luck.  Uninstalled, deleted the folder in Program Files (x86), and reinstalled.  

Got the screen shown below.  Totally unresponsive.  Can't minimize, maximize, close or move the window.

![unity4](https://user-images.githubusercontent.com/106773418/214972104-d24c6328-3ca6-4851-8830-24e3d682d4f4.PNG)

**Comment by bdlukaa** [comment] 2023-01-26 23:43
This looks like a duplicate of #49 and #53. The last should be fixed by #55

**Comment by bdlukaa** [comment] 2023-01-26 23:43
Closing as duplicate

**Closed by bdlukaa** 2023-01-26 23:43 UTC
